# Global LLM configuration
[llm]
model = "qwen3-vl-plus-2025-09-23"
base_url = "https://dashscope.aliyuncs.com/compatible-mode/v1"
api_key = "sk-01559a3f857a4b97ab886ff54bea0c24"
max_tokens = 4096
temperature = 0.0

# Optional configuration for specific LLM models
[llm.vision]
model = "qwen3-vl-plus-2025-09-23"
base_url = "https://dashscope.aliyuncs.com/compatible-mode/v1"
api_key = "sk-01559a3f857a4b97ab886ff54bea0c24"
